### ISSUE TITLE
Cant deploy

### ISSUE THREAD

**Issue by Be1zebub** [CFC-Servers/gm_express_service#4]
![image](https://user-images.githubusercontent.com/34854689/201772469-38ee1fc3-6d72-4812-b013-3f33bf309e99.png)
fork: https://github.com/Be1zebub/gm_express_service  
I think I enabled actions incorrectly, it's just that there was no green "Enable actions" button in the actions tab - so I just created an empty .github/workflows/main.yml  
any ideas how to solve this?

**Comment by sarahsturgeon** [comment]
Uh oh. I haven't done a full setup from a different Cloudflare account/fork yet, so I can't immediately offer any valuable advice.

I suspect it'll be more difficult to set up than I originally suggested.
I will say, I was manually deploying using the wrangler2 CLI, not on Github actions.

Do you think you could reach out to me on Discord so we could work through it more quickly? I'll summarize anything we learn in this issue. **Phatso#2326**

Also, one more thing to note; I have a compatability-breaking (hopefully the only one!) change pending. I'm testing it right now and hope to deploy it later today.

**Comment by sarahsturgeon** [comment]
If you're not able to chat about this issue, that'll be fine; once I deploy the new update, I'll sit down and try to set it up as a new user and document every step of the way.

If you'd prefer, I'll post an update in here when that documentation is available 👍

**Comment by sarahsturgeon** [comment]
Made some great progress today. I think the new branches are ready to be deployed.
I'm going to wait until tomorrow morning, though. That way I can be available if something goes wrong 😅 

I'll use my lunch break to document the Service setup process and then I'll bump this issue one last time.

**Comment by sarahsturgeon** [comment]
I spent a bunch of time taking screenshots and drawing red squares and arrows and stuff, only to realize that I had fucked up originally.
I added the deployment workflow, so now a fresh user should literally just have to click the button and follow the instructions 🤦‍♂️ 

For you, I would suggest deleting the fork that it made last time and letting it redo everything fresh.


Hopefully it's a smooth process! 
Let me know how it goes 👍


[![Deploy to Cloudflare Workers](https://deploy.workers.cloudflare.com/button?paid=true)](https://deploy.workers.cloudflare.com/?url=https://github.com/CFC-Servers/gm_express_service&paid=true)

e: I updated the README with some more instructions that may be helpful: https://github.com/CFC-Servers/gm_express_service

**Comment by Be1zebub** [comment]
ty, it works now
